sudo: required

dist: xenial

language: bash

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/arm/v6"
    - DOCKER_COMMIT=${TRAVIS_COMMIT::6}
    - DOCKER_TAG="${TRAVIS_TAG}"
    - BUILDKIT_HOST=tcp://0.0.0.0:1234
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - secure: at01B/fbMZtfZiABZjVTyyc6jlSxvuKCZfMdXH9p2XurnVMqRMfriURPORcqBec/bqOGMoUlYSlJMT+g2w1CO53HC08dhniNq9cl5CmR4AhrMFzLIb7iW5KxdXmLOf/DrlYr9+wj7RILxJKDvsTCnehAzOGUBmaRnxFTKaLmXmdUOym5iz1w4hsQe5HE2wC/mzHc8mNZCSdNycvPIFPrO8R/lDhKokIvnQpwwBZisBCVkXd6dp2354GBeIcoYMq+B8uAosPHHhptu5Pbue1fWT4woX97E79PgxWxYcubkueohPIzfCm9MFNR8HuA9DuH3eUt7KYwHjZwIg8ysrMC8TshZkvT9glDTOgm+2785fkK+4IidqSk7cU8W5FGni+No+Ptgx703Na6ZHI76261uqK+k+u2hGNZjrb+3U7OJ15jnJnd1mGsEiEH1Z0oB0bi5sPb97RT1IA4amDorblYfJqaycrVdfoM7923Myjqy07cU+PKDQdsCHuPSEB8v8YHEVaQuCavDOHMeXL/yUEnKgXnUKoMm22r/W34xfYCl8MNU+H+4cDlnhiltmhhrhDhuJu/LsQYtNoMEFP+Xzs7TKAZvdwAem4/O9IMATxs8YLc+LzVG+a0lgRoZMUvmXMqI+PL43CAvvn5WoTWRAG2wDKw1JE0CLii7q63/He6DjI=
    
addons:
  apt:
    packages:
      - docker-ce

git:
  depth: 1

before_install: >
  ./.travis/setup.sh \
    "${DOCKER_PLATFORMS}"

jobs:
  include:
    - script: >
        ./.travis/build.sh \
          "${DOCKER_IMAGE}" \
          "${DOCKER_COMMIT}" \
          "${DOCKER_PLATFORMS}"

deploy:
  provider: script
  script: >-
    bash ./.travis/push.sh
    "${DOCKER_IMAGE}"
    "${DOCKER_COMMIT}"
    "${DOCKER_TAG}"
    "${DOCKER_PLATFORMS}"
  on:
    tags: true

notifications:
  email: false
