dist: xenial
os: linux
language: shell

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/386"
    - DOCKER_COMMIT=${TRAVIS_COMMIT::6}
    - DOCKER_TAG="${TRAVIS_TAG}"
    - DOCKER_IMAGE="bademux/openlighting"
    - secure: hWm6MLABydcD9u4gskTZ+IsEPg1I5tGmRL3SmjGXaixjMeIWLwzMefZt+S38710fqfFD7XIhAJ5b5LZCaPCCbo1smXPnUNMfHnbfxZ7vafCvtYbspuRdWygJMKsi6VWnPUeDBGshxau82NErivOr+wXBppJSpqAVHiN1dsUwWJeCqIe4nG6YiwrTTFzACf/ZrbkiX/cemF+aQ2un+mAQu7hbWPoCfq6dJhu+Ydab/qVeobxOE18v6qXGyvC5H17HpI8/ch2zS2VeIlsHOnuUA8tq4BnfDSumo/VCdO3B5wVQjy/CQ4mTMcNMy1955e3zA4xMpF3IY+G5/e0/DPAGXlPrUuCvu3FqB/bfclLAcbSjgj7kBg5JNw9aCashFKiK7yXjQHQCRilHdKZlAY+0Nl6OBf/lpLmdjlImMkaXcBNgrWIQ1uH8Nqt9SMFd1ygwcsVQOxCZy8qe4fvc5Bmq0l2TOVYK7V8L9uY+TluRzr0lr9Fb8hSrk/wd5WHdvGgn46VWZIOwPG0quyoA6Y6yDoC0j2CrncFH1gdU/Rwxq++k+9JQJMYcqb+4xDFIH927+8UDIEOjupu0FUrFIEp2e0pgCaigRM2f4ntvFCgkQmRcuoRsmw+rAaPPT6LQUw1UhFBWPky9/3JMXSYSqelf5NwWyFMTMRGJrxuQQLtwcHE=

git:
  depth: 1

before_install: bash ./.travis/builder.sh pre_install
after_success: bash ./.travis/builder.sh post_install
after_failure: bash ./.travis/builder.sh post_install

stages:
  - name: build_amd64
    if: branch != master AND tag IS blank
  - name: build_and_deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

matrix:
  include:
    - stage: build_amd64
      script: bash ./.travis/builder.sh build ${DOCKER_IMAGE} ${DOCKER_COMMIT} "linux/amd64"
    - stage: build_and_deploy
      script: bash ./.travis/builder.sh build_and_deploy ${DOCKER_IMAGE} ${DOCKER_TAG} ${DOCKER_PLATFORMS}

notifications:
  email: false
